"""empty message

Revision ID: c2a1ffd947a3
Revises: b9deb2e995b9
Create Date: 2021-01-24 22:57:38.269933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a1ffd947a3'
down_revision = 'b9deb2e995b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('build_item', sa.String(length=2048), nullable=True),
    sa.Column('support_socket', sa.String(length=2048), nullable=True),
    sa.Column('counter', sa.String(length=2048), nullable=True),
    sa.Column('be_countered', sa.String(length=2048), nullable=True),
    sa.Column('skill_up', sa.String(length=2048), nullable=True),
    sa.Column('how_to_play', sa.String(length=2048), nullable=True),
    sa.Column('combo', sa.String(length=2048), nullable=True),
    sa.Column('combine_with', sa.String(length=2048), nullable=True),
    sa.Column('how_to_use_skill', sa.String(length=2048), nullable=True),
    sa.Column('introduce', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_question', sa.String(length=2048), nullable=True),
    sa.Column('message_answer', sa.String(length=2048), nullable=True),
    sa.Column('intent', sa.String(length=2048), nullable=True),
    sa.Column('action', sa.String(length=2048), nullable=True),
    sa.Column('entities', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=256), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'name')
    op.drop_table('conversation')
    op.drop_table('champion')
    # ### end Alembic commands ###
